name: build-pages
run-name: Build GitHub Pages
on: [push]
jobs:
    build-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.5
            - uses: actions/setup-python@v5.1.0
            - run: python -V
